// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bprgwoxpdjovqashllvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwcmd3b3hwZGpvdnFhc2hsbHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTk0NzYsImV4cCI6MjA1ODIzNTQ3Nn0.y59Fpx0OZFXycvRnkYvxB_GytFeg9iSunkzyMetc2eA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);